micronaut:
  security:
    endpoints:
      login:
        enabled: true
    authentication: bearer
    interceptUrlMap:
      - pattern: "/swagger/**"
        httpMethod: GET
        access:
          - isAnonymous()
      - pattern: "/swagger-ui/**"
        httpMethod: GET
        access:
          - isAnonymous()
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/micronaut
    driverClassName: org.postgresql.Driver
    username: postgres
    password: '1010100'
jpa.default:
  entity-scan:
    packages: br.com.estudo.domain.models
  properties.hibernate.hbm2ddl.auto: update
flyway:
  datasources:
    default:
      enabled: true

#TODO: Com esse configuraçao abaixo o micronaut formata todas as datas de resposta no JSON (LocalDate, LocalDateTime)
jackson:
  date-format: 'yyyy-MM-dd HH:mm:ss'
